version: '3.8'

services:
  web:
    build: ./odoo
    ports:
      - "8071:8071"
    environment:
      - HOST=0.0.0.0
      - PORT=8071
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - ADMIN_PASSWD=pass123$
    volumes:
      - ./odoo/custom_addons:/mnt/extra-addons
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
