[phases.setup]
apt_pkgs = ["git", "libxml2-dev", "libxslt-dev", "libpq-dev", "python3-dev", "build-essential"]
python_version = "3.10"


[phases.build]
cmds = ["chmod +x start.sh"]

[phases.start]
cmd = "./start.sh"
