FROM odoo:16.0

# Copy custom addons to Odoo extra-addons folder
COPY ./custom_addons /mnt/extra-addons

# Set Odoo addons path environment variable
ENV ODOO_ADDONS_PATH=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

# Expose your port
EXPOSE 8071

# Start Odoo with your config file (make sure to copy or mount it)
CMD ["odoo", "-c", "/etc/odoo/odoo.conf"]
